"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _dashboard_stats_kpi from './dashboard-stats-kpi.bones.json'
import _my_reports_responses_summary from './my-reports-responses-summary.bones.json'
import _my_reports_attendance_summary from './my-reports-attendance-summary.bones.json'
import _my_reports_summary_respondents from './my-reports-summary-respondents.bones.json'
import _my_reports_summary_question from './my-reports-summary-question.bones.json'

configureBoneyard({"color":"#261A36","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#333333","speed":"2s","shimmerAngle":110,"stagger":80,"transition":300})

registerBones({
  "dashboard-stats-kpi": _dashboard_stats_kpi,
  "my-reports-responses-summary": _my_reports_responses_summary,
  "my-reports-attendance-summary": _my_reports_attendance_summary,
  "my-reports-summary-respondents": _my_reports_summary_respondents,
  "my-reports-summary-question": _my_reports_summary_question,
})
