"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _my_response_summary from './my-response-summary.bones.json'
import _my_response_summary_question_0 from './my-response-summary-question.bones.json'
import _dashboard_stats_kpi from './dashboard-stats-kpi.bones.json'

configureBoneyard({"color":"#261A36","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#333333","speed":"2s","shimmerAngle":110,"stagger":80,"transition":300})

registerBones({
  "my-response-summary": _my_response_summary,
  "my-response-summary-question-0": _my_response_summary_question_0,
  "dashboard-stats-kpi": _dashboard_stats_kpi,
})
